#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get install -y haproxy=2.9.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 333499-web-01 34.229.136.28 check
   server 333499-web-02 52.87.216.230 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start